### ISSUE TITLE
Error when running the compiled from source executable

### ISSUE THREAD

**Issue by Joh11** [sanette/randomize#1]
After using `make` or `make nc`, when I try to execute `randomize`, I get the following error:
```
cp: impossible to evaluate '$HOME/.opam/4.11.0/lib/bogue/../../share/bogue/themes.tgz': No such file or directory
Fatal error: exception Not_found
```

**Comment by sanette** [comment]
I'm sorry I didn't get a notification for this :(

Just in case: this is solved in newer versions because the `themes.tgz` file is no more necessary.
